CREATE TABLE IF NOT EXISTS todos (
	id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name        text NOT NULL CHECK (name <> ''),
    priority    integer NOT NULL,
    description text,
    duedate 	date NOT NULL    
);